# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Task Manager CI/CD

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ "master" ]

jobs:
#  build:
#    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        node-version: [18.x]
#    name: Node ${{ matrix.node-version }} tests
#    steps:
#    - uses: actions/checkout@v3
#    - name: Tests using Node.js ${{ matrix.node-version }}
#      uses: actions/setup-node@v3
#      with:
#        node-version: ${{ matrix.node-version }}
#    - run: npm ci
#      env:
#        PORT: ${{ vars.PORT }}
#        MONGODB_URL: ${{ secrets.MONGODB_TEST_URL }}
#        JWT_SECRET: ${{ secrets.JWT_SECRET }}
#    - run: npm run test-gitflow

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run Jest tests
        env:
          PORT: ${{ vars.PORT }}
          MONGODB_URL: ${{ secrets.MONGODB_TEST_URL }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: npm run test-gitflow
    
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@main
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
